all:
	javac CMST.java

test1:
	java CMST {{0,5,6,9,12,15},{0,0,4,3,8,10},{0,0,0,8,5,12},{0,0,0,0,6,6},{0,0,0,0,0,7},{0,0,0,0,0,0}}

test2:
	java CMST [your-parameters-for-test2]

test3:
	java CMST [your-parameters-for-test3]

test4:
	java CMST [your-parameters-for-test4]